package com.pukhova.domain;

// Generated 08.12.2013 23:24:28 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Photos generated by hbm2java
 */
@Entity
@Table(name = "photos", catalog = "share_it")
public class Photos implements java.io.Serializable {

	private Integer photoId;
	private Items items;
	private String relativePath;

	public Photos() {
	}

	public Photos(Items items, String relativePath) {
		this.items = items;
		this.relativePath = relativePath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "photoId", unique = true, nullable = false)
	public Integer getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(Integer photoId) {
		this.photoId = photoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemId")
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@Column(name = "relativePath", length = 130)
	public String getRelativePath() {
		return this.relativePath;
	}

	public void setRelativePath(String relativePath) {
		this.relativePath = relativePath;
	}

}
